name: DiscoSheep
main: Goldsack.DiscoSheep.DiscoSheep
version: ${version}
author: chrisward
description: Gets sheeps into partymode
commands:
  ds:
    description: Gets sheeps into partymode
    usage: |
           /<command> color to toggle all sheeps going rainbowmode
           /<command> stop to end party
           You can mix up the commands and include it in any order you like.
           Example: /<command> david john sheep:10 creeper:5 time:4 distance:8
           to give david and john a party with 10 sheeps, 5 creepers, that
           lasts for 4 sec and spawns within 8 blocks of them.
           You can also use s:10 c:5 t:4 d:8 as shortcuts.
           Use "all" to give every player a party time! Untz Untz!
    aliases: [discosheep, discoparty, disco]
    permission: discosheep.help
permissions:
  discosheep.*:
    description: Grants you access to all of DiscoSheep's commands
    default: op
    children:
      discosheep.party.one: true
      discosheep.party.many: true
      discosheep.mob.sheep: true
      discosheep.mob.creeper: true
      discosheep.stop: true
      discosheep.color: true
      discosheep.reload: true
      discosheep.help: true
  discosheep.party.*:
    default: op
    children:
      discosheep.party.one: true
      discosheep.party.many: true
  discosheep.mob.*:
    default: op
    children:
      discosheep.mob.sheep: true
      discosheep.mob.creeper: true
  discosheep.party.one:
    default: op
  discosheep.party.many:
    default: op
  discosheep.mob.sheep:
    default: op
  discosheep.mob.creeper:
    default: op
  discosheep.stop:
    default: op
  discosheep.color:
    default: op
  discosheep.reload:
    default: op
  discosheep.help:
    default: op